import core, {
  createTwClassDictionary,
  ResolvedTailwindConfig,
} from "@xwind/core";

import initTwClassesUtils, {
  TwClasses,
  TwParsedClass,
} from "@xwind/class-utilities";

function tailwind(
  tailwindConfig: ResolvedTailwindConfig,
  includeBase: boolean
) {
  const {
    resolvedConfig,
    utilitiesRoot,
    componentsRoot,
    baseRoot,
    screens,
    variants,
    generateTwClassSubstituteRoot,
  } = core(tailwindConfig);

  const twClassDictionary = createTwClassDictionary(
    componentsRoot,
    utilitiesRoot
  );

  const baseCSSroot = baseRoot.clone();
  baseCSSroot.walkAtRules("layer", (atRule) => {
    atRule.replaceWith(atRule.nodes);
  });

  const compare = (
    { class: firstClass, variants: firstVariants }: TwParsedClass,
    { class: secondClass, variants: secondVariants }: TwParsedClass
  ) => {
    const firstIsScreen = screens.indexOf(firstVariants[0]);
    const secondIsScreen = screens.indexOf(secondVariants[0]);
    if (firstIsScreen !== -1 || secondIsScreen !== -1) {
      if (firstIsScreen < secondIsScreen) {
        return -1;
      }
      if (firstIsScreen > secondIsScreen) {
        return 1;
      }
      return 0;
    }

    if (firstClass < secondClass) {
      return -1;
    }

    if (firstClass > secondClass) {
      return 1;
    }
    return 0;
  };

  const twClassesUtils = initTwClassesUtils(resolvedConfig.separator, [
    ...screens,
    ...variants,
  ]);

  const generatedTwClassesCSS: { [key: string]: string } = {};

  return (twClasses: TwClasses) => {
    const sortedTwClasses = twClassesUtils.parser(twClasses).sort(compare);
    const combinedRoot: string[] = [];
    for (const twClass of sortedTwClasses) {
      const [generatedTwClass] = twClassesUtils.generator(twClass);

      let generatedTwClassCSS = generatedTwClassesCSS[generatedTwClass];

      if (!generatedTwClassCSS) {
        generatedTwClassCSS = generateTwClassSubstituteRoot(
          twClassDictionary,
          twClass
        ).toString();
        generatedTwClassesCSS[generatedTwClass] = generatedTwClassCSS;
      }
      combinedRoot.push(generatedTwClassCSS);
    }

    if (!includeBase) {
      return ["/* Generated by @xwind/babel-plugin */", ...combinedRoot].join(
        "\n"
      );
    }
    return [
      "/* Generated by @xwind/babel-plugin */",
      baseCSSroot.toString(),
      ...combinedRoot,
    ].join("\n");
  };
}

export default tailwind;
